// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByiwtQFAFrffkAWZp088P9VUYOZSn98I4',
    appId: '1:727100546301:web:8fd21b29fcebec889ab294',
    messagingSenderId: '727100546301',
    projectId: 'green-house2-a',
    authDomain: 'green-house2-a.firebaseapp.com',
    databaseURL: 'https://green-house2-a-default-rtdb.firebaseio.com',
    storageBucket: 'green-house2-a.appspot.com',
    measurementId: 'G-ZG920GF5M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs42SlGBFQKfL_kE3yTMZLSWHzshqAN28',
    appId: '1:727100546301:android:c5ae589400b09e5d9ab294',
    messagingSenderId: '727100546301',
    projectId: 'green-house2-a',
    databaseURL: 'https://green-house2-a-default-rtdb.firebaseio.com',
    storageBucket: 'green-house2-a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByiwtQFAFrffkAWZp088P9VUYOZSn98I4',
    appId: '1:727100546301:web:57124f4b02d0641e9ab294',
    messagingSenderId: '727100546301',
    projectId: 'green-house2-a',
    authDomain: 'green-house2-a.firebaseapp.com',
    databaseURL: 'https://green-house2-a-default-rtdb.firebaseio.com',
    storageBucket: 'green-house2-a.appspot.com',
    measurementId: 'G-6G4YJ1DBYF',
  );
}
